### ISSUE TITLE
add `disclose_publisher`

### ISSUE THREAD

**Issue by goeddea** [tavendo/WAMP#122] opened 2015-01-14 15:29 UTC
With RPCs, the caller can choose to disclose details about himself, and the callee can request the caller's details.
With PubSub events, the publisher can choose to disclose details about himself, but subscribers do not have the possibility to request a publisher's details.
This seems an odd asymmetry in the protocol.

**Comment by oberstet** [comment] 2015-09-01 21:38
duplicate of https://github.com/tavendo/WAMP/issues/57

**Closed by oberstet** 2015-09-01 21:38 UTC
Labels: Advanced Profile
