### ISSUE TITLE
'disclose caller' not properly disclosed in spec

### ISSUE THREAD

**Issue by goeddea** [tavendo/WAMP#101] opened 2014-10-24 14:15 UTC
In the advanced spec, under [Caller Identification](https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#caller-identification), only a Caller requesting that his caller information be transmitted to the Callee is explicitly mentioned.
There is no mention of a Callee requesting this information ("disclose_caller"), or whether the Dealer can deny this request.

**Comment by oberstet** [comment] 2015-09-01 21:38
duplicate of https://github.com/tavendo/WAMP/issues/57

**Closed by oberstet** 2015-09-01 21:38 UTC
Labels: Advanced Profile
